db.url=jdbc:h2:mem:biblioteca_fiap;DB_CLOSE_DELAY=-1;MODE=MySQL;TRACE_LEVEL_SYSTEM_OUT=3
db.username=sa
db.password=
db.driver=org.h2.Driver


#HikariCp -> Connection Pool
hikari.pool.name=FIAP-H2_Pool
hikari.maximum.pool.size=10
hikari.minimum.idle=2
hikari.connection.timeout=30000
hikari.idle.timeout=60000
hikari.auto.commit=true